name: remote-sensing
channels:
  - conda-forge
  - plotly
  - defaults
dependencies:
  - python=3.8
  - pandas=1.4
  - matplotlib
  - geopandas=0.9
  - rasterio=1.2
  - rasterstats=0.16
  - webdavclient3=3.14
  - python-dotenv=0.19
  - seaborn=0.11
  - pip
  - pip:
    - cbsodata=1.3.4
